// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit by hand.
// Regenerate after every `drizzle-kit generate`.
export const migrationBundle = {
  "journal": {
    "version": "7",
    "dialect": "sqlite",
    "entries": [
      {
        "idx": 0,
        "version": "6",
        "when": 1782448853803,
        "tag": "0000_amusing_swordsman",
        "breakpoints": true
      },
      {
        "idx": 1,
        "version": "6",
        "when": 1782450165627,
        "tag": "0001_magical_killraven",
        "breakpoints": true
      },
      {
        "idx": 2,
        "version": "6",
        "when": 1782452634455,
        "tag": "0002_living_captain_america",
        "breakpoints": true
      },
      {
        "idx": 3,
        "version": "6",
        "when": 1782457233565,
        "tag": "0003_rare_captain_america",
        "breakpoints": true
      },
      {
        "idx": 4,
        "version": "6",
        "when": 1782458502422,
        "tag": "0004_flowery_polaris",
        "breakpoints": true
      },
      {
        "idx": 5,
        "version": "6",
        "when": 1782462667570,
        "tag": "0005_far_mattie_franklin",
        "breakpoints": true
      },
      {
        "idx": 6,
        "version": "6",
        "when": 1782463643197,
        "tag": "0006_slim_spitfire",
        "breakpoints": true
      },
      {
        "idx": 7,
        "version": "6",
        "when": 1782466133414,
        "tag": "0007_nifty_wallop",
        "breakpoints": true
      },
      {
        "idx": 8,
        "version": "6",
        "when": 1782467308754,
        "tag": "0008_dusty_union_jack",
        "breakpoints": true
      },
      {
        "idx": 9,
        "version": "6",
        "when": 1782467593911,
        "tag": "0009_dry_dagger",
        "breakpoints": true
      },
      {
        "idx": 10,
        "version": "6",
        "when": 1782469202021,
        "tag": "0010_absurd_mentor",
        "breakpoints": true
      },
      {
        "idx": 11,
        "version": "6",
        "when": 1782469500000,
        "tag": "0011_append_only_audit",
        "breakpoints": true
      },
      {
        "idx": 12,
        "version": "6",
        "when": 1782471061451,
        "tag": "0012_cute_darkstar",
        "breakpoints": true
      },
      {
        "idx": 13,
        "version": "6",
        "when": 1782477212269,
        "tag": "0013_shallow_dark_phoenix",
        "breakpoints": true
      },
      {
        "idx": 14,
        "version": "6",
        "when": 1782478957270,
        "tag": "0014_married_warstar",
        "breakpoints": true
      },
      {
        "idx": 15,
        "version": "6",
        "when": 1782484919187,
        "tag": "0015_mixed_timeslip",
        "breakpoints": true
      },
      {
        "idx": 16,
        "version": "6",
        "when": 1782485300231,
        "tag": "0016_empty_kulan_gath",
        "breakpoints": true
      },
      {
        "idx": 17,
        "version": "6",
        "when": 1782488587471,
        "tag": "0017_sticky_baron_zemo",
        "breakpoints": true
      },
      {
        "idx": 18,
        "version": "6",
        "when": 1782488986782,
        "tag": "0018_pale_nighthawk",
        "breakpoints": true
      },
      {
        "idx": 19,
        "version": "6",
        "when": 1782498208803,
        "tag": "0019_high_ink",
        "breakpoints": true
      },
      {
        "idx": 20,
        "version": "6",
        "when": 1782501783905,
        "tag": "0020_nostalgic_lockheed",
        "breakpoints": true
      },
      {
        "idx": 21,
        "version": "6",
        "when": 1782503125698,
        "tag": "0021_backfill_matter_lead",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `Intake` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`category` text DEFAULT 'CIVIL_COMMERCIAL' NOT NULL,\n\t`status` text DEFAULT 'INTAKE' NOT NULL,\n\t`claim_amount` text,\n\t`client_name` text NOT NULL,\n\t`declined_reason` text,\n\t`created_by_id` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `User` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`role` text DEFAULT 'LAWYER' NOT NULL,\n\t`active` integer DEFAULT true NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `User_email_unique` ON `User` (`email`);",
    "m0001": "CREATE TABLE `ConflictCheck` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`intake_id` text,\n\t`query_name` text,\n\t`query_id_number` text,\n\t`candidate_role` text NOT NULL,\n\t`top_severity` text NOT NULL,\n\t`hit_count` integer NOT NULL,\n\t`checked_by_id` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `Counter` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` integer DEFAULT 0 NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `Matter` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`internal_code` text NOT NULL,\n\t`title` text NOT NULL,\n\t`category` text NOT NULL,\n\t`status` text DEFAULT 'PENDING_ACCEPTANCE' NOT NULL,\n\t`claim_amount` text,\n\t`primary_client_name` text,\n\t`our_standing` text,\n\t`owner_id` text NOT NULL,\n\t`intake_id` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `Matter_internal_code_unique` ON `Matter` (`internal_code`);--> statement-breakpoint\nCREATE INDEX `Matter_status_idx` ON `Matter` (`status`);--> statement-breakpoint\nCREATE TABLE `Party` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`intake_id` text,\n\t`matter_id` text,\n\t`role` text NOT NULL,\n\t`name` text NOT NULL,\n\t`id_number` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Party_name_idx` ON `Party` (`name`);--> statement-breakpoint\nCREATE INDEX `Party_idnum_idx` ON `Party` (`id_number`);",
    "m0002": "CREATE TABLE `MatterProcedure` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`engagement` text DEFAULT 'ENGAGED' NOT NULL,\n\t`order` integer NOT NULL,\n\t`case_number` text,\n\t`handling_agency` text,\n\t`handler` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`outcome` text,\n\t`accepted_at` integer,\n\t`concluded_at` integer,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `MatterProcedure_matter_order_uq` ON `MatterProcedure` (`matter_id`,`order`);",
    "m0003": "CREATE TABLE `Deadline` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`procedure_id` text NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`category` text DEFAULT 'CUSTOM' NOT NULL,\n\t`title` text NOT NULL,\n\t`due_at` integer NOT NULL,\n\t`basis` text,\n\t`source_event` text,\n\t`auto_computed` integer DEFAULT false NOT NULL,\n\t`completed` integer DEFAULT false NOT NULL,\n\t`completed_at` integer,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Deadline_matter_idx` ON `Deadline` (`matter_id`);--> statement-breakpoint\nCREATE INDEX `Deadline_due_idx` ON `Deadline` (`due_at`,`completed`);",
    "m0004": "CREATE TABLE `PreservationRenewal` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`preservation_id` text NOT NULL,\n\t`old_expiry_date` integer NOT NULL,\n\t`new_expiry_date` integer NOT NULL,\n\t`renewed_at` integer NOT NULL,\n\t`performed_by_id` text NOT NULL,\n\t`note` text\n);\n--> statement-breakpoint\nCREATE INDEX `PreservationRenewal_pres_idx` ON `PreservationRenewal` (`preservation_id`);--> statement-breakpoint\nCREATE TABLE `Preservation` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`property_type` text NOT NULL,\n\t`amount` text,\n\t`respondent` text,\n\t`guarantee_type` text,\n\t`start_date` integer NOT NULL,\n\t`duration_days` integer NOT NULL,\n\t`expiry_date` integer NOT NULL,\n\t`status` text DEFAULT 'ACTIVE' NOT NULL,\n\t`remind_days` text DEFAULT '[30,15,7,3,1]' NOT NULL,\n\t`owner_id` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Preservation_matter_idx` ON `Preservation` (`matter_id`);--> statement-breakpoint\nCREATE INDEX `Preservation_expiry_idx` ON `Preservation` (`status`,`expiry_date`);",
    "m0005": "CREATE TABLE `Client` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`type` text DEFAULT 'INDIVIDUAL' NOT NULL,\n\t`id_number` text,\n\t`phone` text,\n\t`email` text,\n\t`address` text,\n\t`source` text,\n\t`notes` text,\n\t`deleted_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Client_name_idx` ON `Client` (`name`);--> statement-breakpoint\nCREATE INDEX `Client_idnum_idx` ON `Client` (`id_number`);--> statement-breakpoint\nCREATE TABLE `Contact` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`client_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`title` text,\n\t`phone` text,\n\t`email` text,\n\t`is_primary` integer DEFAULT false NOT NULL,\n\t`notes` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Contact_client_idx` ON `Contact` (`client_id`);",
    "m0006": "CREATE TABLE `Hearing` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`procedure_id` text NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`room` text,\n\t`address` text,\n\t`judge` text,\n\t`starts_at` integer NOT NULL,\n\t`ends_at` integer,\n\t`notes` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Hearing_matter_idx` ON `Hearing` (`matter_id`,`starts_at`);--> statement-breakpoint\nCREATE TABLE `Note` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`author_id` text NOT NULL,\n\t`channel` text DEFAULT 'OTHER' NOT NULL,\n\t`with_whom` text,\n\t`occurred_at` integer NOT NULL,\n\t`content` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Note_matter_idx` ON `Note` (`matter_id`,`occurred_at`);--> statement-breakpoint\nCREATE TABLE `Task` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`assignee_id` text,\n\t`due_at` integer,\n\t`completed` integer DEFAULT false NOT NULL,\n\t`completed_at` integer,\n\t`created_by_id` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Task_matter_idx` ON `Task` (`matter_id`,`completed`);",
    "m0007": "CREATE TABLE `Billing` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`contract_amount` text NOT NULL,\n\t`schedule` text,\n\t`status` text DEFAULT 'DRAFT' NOT NULL,\n\t`signed_at` integer,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Billing_matter_idx` ON `Billing` (`matter_id`);--> statement-breakpoint\nCREATE TABLE `CommissionPlan` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`percent` text NOT NULL,\n\t`label` text,\n\t`active` integer DEFAULT true NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `CommissionPlan_matter_user_uq` ON `CommissionPlan` (`matter_id`,`user_id`);--> statement-breakpoint\nCREATE TABLE `FeeEntry` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`billing_id` text,\n\t`type` text NOT NULL,\n\t`amount` text NOT NULL,\n\t`occurred_at` integer NOT NULL,\n\t`invoice_no` text,\n\t`payer_or_payee` text,\n\t`method` text,\n\t`note` text,\n\t`parent_fee_entry_id` text,\n\t`beneficiary_user_id` text,\n\t`recorded_by_id` text NOT NULL,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `FeeEntry_matter_idx` ON `FeeEntry` (`matter_id`,`type`);--> statement-breakpoint\nCREATE INDEX `FeeEntry_parent_idx` ON `FeeEntry` (`parent_fee_entry_id`);",
    "m0008": "CREATE TABLE `ArchiveRecord` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`checklist_json` text DEFAULT '{}' NOT NULL,\n\t`missing_items` text DEFAULT '[]' NOT NULL,\n\t`force_reason` text,\n\t`archived_by_id` text NOT NULL,\n\t`archived_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `ArchiveRecord_matter_idx` ON `ArchiveRecord` (`matter_id`);",
    "m0009": "DROP INDEX `ArchiveRecord_matter_idx`;--> statement-breakpoint\n-- Repair any duplicate ArchiveRecord rows for a matter (possible before the\n-- unique constraint / atomic archive claim existed), keeping the earliest row,\n-- so CREATE UNIQUE INDEX below cannot abort the migration on existing data.\nDELETE FROM `ArchiveRecord` WHERE `rowid` NOT IN (\n  SELECT MIN(`rowid`) FROM `ArchiveRecord` GROUP BY `matter_id`\n);--> statement-breakpoint\nCREATE UNIQUE INDEX `ArchiveRecord_matter_uq` ON `ArchiveRecord` (`matter_id`);",
    "m0010": "CREATE TABLE `AuditLog` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text,\n\t`action` text NOT NULL,\n\t`target_type` text,\n\t`target_id` text,\n\t`detail_json` text,\n\t`ip` text,\n\t`user_agent` text,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `AuditLog_user_idx` ON `AuditLog` (`user_id`,`created_at`);--> statement-breakpoint\nCREATE INDEX `AuditLog_action_idx` ON `AuditLog` (`action`,`created_at`);",
    "m0011": "-- Enforce AuditLog append-only at the storage boundary, not just by\n-- convention: any UPDATE or DELETE aborts, even from a future code path,\n-- migration, or admin shell sharing this DB handle. IF NOT EXISTS so the\n-- migration is idempotent across fresh and already-upgraded databases.\nCREATE TRIGGER IF NOT EXISTS `AuditLog_no_update` BEFORE UPDATE ON `AuditLog`\nBEGIN\n\tSELECT RAISE(ABORT, 'AuditLog is append-only');\nEND;--> statement-breakpoint\nCREATE TRIGGER IF NOT EXISTS `AuditLog_no_delete` BEFORE DELETE ON `AuditLog`\nBEGIN\n\tSELECT RAISE(ABORT, 'AuditLog is append-only');\nEND;\n",
    "m0012": "CREATE TABLE `DocumentFolder` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`order_index` integer DEFAULT 0 NOT NULL,\n\t`is_default` integer DEFAULT false NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `DocumentFolder_matter_name_uq` ON `DocumentFolder` (`matter_id`,`name`);--> statement-breakpoint\nCREATE INDEX `DocumentFolder_matter_idx` ON `DocumentFolder` (`matter_id`,`order_index`);--> statement-breakpoint\nCREATE TABLE `Document` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text,\n\t`intake_id` text,\n\t`procedure_id` text,\n\t`folder_id` text,\n\t`name` text NOT NULL,\n\t`category` text DEFAULT 'OTHER' NOT NULL,\n\t`source_party` text,\n\t`status` text DEFAULT 'DRAFT' NOT NULL,\n\t`reviewed_by_id` text,\n\t`reviewed_at` integer,\n\t`approved_by_id` text,\n\t`approved_at` integer,\n\t`version` integer DEFAULT 1 NOT NULL,\n\t`is_latest` integer DEFAULT true NOT NULL,\n\t`family_id` text,\n\t`storage_key` text,\n\t`mime_type` text,\n\t`size` integer,\n\t`sha256` text,\n\t`tags_json` text DEFAULT '[]' NOT NULL,\n\t`uploaded_by_id` text NOT NULL,\n\t`deleted_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Document_matter_idx` ON `Document` (`matter_id`,`category`);--> statement-breakpoint\nCREATE INDEX `Document_intake_idx` ON `Document` (`intake_id`);--> statement-breakpoint\nCREATE INDEX `Document_folder_idx` ON `Document` (`folder_id`);--> statement-breakpoint\nCREATE INDEX `Document_family_idx` ON `Document` (`family_id`);",
    "m0013": "CREATE TABLE `SealRequest` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`seal_type` text NOT NULL,\n\t`matter_id` text,\n\t`purpose` text NOT NULL,\n\t`document_title` text NOT NULL,\n\t`page_count` integer DEFAULT 1 NOT NULL,\n\t`require_cross_page_seal` integer DEFAULT false NOT NULL,\n\t`copies` integer DEFAULT 1 NOT NULL,\n\t`urgency` text DEFAULT 'NORMAL' NOT NULL,\n\t`draft_doc_id` text NOT NULL,\n\t`stamped_doc_id` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`request_note` text,\n\t`approve_note` text,\n\t`requested_by_id` text NOT NULL,\n\t`requested_at` integer NOT NULL,\n\t`approved_by_id` text,\n\t`approved_at` integer,\n\t`stamped_by_id` text,\n\t`stamped_at` integer,\n\t`rejected_at` integer,\n\t`parent_seal_request_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `SealRequest_code_unique` ON `SealRequest` (`code`);--> statement-breakpoint\nCREATE UNIQUE INDEX `SealRequest_draft_doc_id_unique` ON `SealRequest` (`draft_doc_id`);--> statement-breakpoint\nCREATE UNIQUE INDEX `SealRequest_stamped_doc_id_unique` ON `SealRequest` (`stamped_doc_id`);--> statement-breakpoint\nCREATE INDEX `SealRequest_status_idx` ON `SealRequest` (`status`,`requested_at`);--> statement-breakpoint\nCREATE INDEX `SealRequest_requester_idx` ON `SealRequest` (`requested_by_id`,`status`);--> statement-breakpoint\nCREATE INDEX `SealRequest_type_idx` ON `SealRequest` (`seal_type`,`status`);--> statement-breakpoint\nCREATE INDEX `SealRequest_matter_idx` ON `SealRequest` (`matter_id`);--> statement-breakpoint\nCREATE TABLE `SystemSetting` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value_json` text NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
    "m0014": "CREATE TABLE `SmsMessage` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`raw_text` text NOT NULL,\n\t`received_at` integer NOT NULL,\n\t`received_by_id` text NOT NULL,\n\t`parsed_json` text NOT NULL,\n\t`sms_type` text DEFAULT 'OTHER' NOT NULL,\n\t`matched_matter_id` text,\n\t`matched_by` text DEFAULT 'UNMATCHED' NOT NULL,\n\t`generated_hearing_id` text,\n\t`generated_deadline_id` text,\n\t`processed` integer DEFAULT false NOT NULL,\n\t`processed_at` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `SmsMessage_receiver_idx` ON `SmsMessage` (`received_by_id`,`processed`,`received_at`);--> statement-breakpoint\nCREATE INDEX `SmsMessage_matter_idx` ON `SmsMessage` (`matched_matter_id`);--> statement-breakpoint\nCREATE INDEX `SmsMessage_type_idx` ON `SmsMessage` (`sms_type`,`received_at`);",
    "m0015": "CREATE INDEX `FeeEntry_occurred_idx` ON `FeeEntry` (`occurred_at`,`type`);",
    "m0016": "CREATE TABLE `Notification` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`priority` text DEFAULT 'NORMAL' NOT NULL,\n\t`title` text NOT NULL,\n\t`content` text,\n\t`href` text,\n\t`ref_type` text,\n\t`ref_id` text,\n\t`read` integer DEFAULT false NOT NULL,\n\t`read_at` integer,\n\t`created_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `Notification_user_unread_idx` ON `Notification` (`user_id`,`read`,`created_at`);--> statement-breakpoint\nCREATE INDEX `Notification_user_idx` ON `Notification` (`user_id`,`created_at`);",
    "m0017": "CREATE INDEX `Hearing_starts_idx` ON `Hearing` (`starts_at`);--> statement-breakpoint\nCREATE INDEX `Task_due_idx` ON `Task` (`due_at`);",
    "m0018": "CREATE TABLE `InvoiceRequest` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text,\n\t`no_matter_reason` text,\n\t`amount` text NOT NULL,\n\t`title` text,\n\t`status` text DEFAULT 'PENDING' NOT NULL,\n\t`request_note` text,\n\t`invoice_type` text,\n\t`invoice_item` text,\n\t`buyer_name` text,\n\t`buyer_tax_no` text,\n\t`buyer_address` text,\n\t`buyer_phone` text,\n\t`buyer_bank` text,\n\t`buyer_bank_account` text,\n\t`evidence_doc_ids_json` text DEFAULT '[]' NOT NULL,\n\t`invoice_no` text,\n\t`issued_at` integer,\n\t`requested_by_id` text NOT NULL,\n\t`requested_at` integer NOT NULL,\n\t`processed_by_id` text,\n\t`processed_at` integer,\n\t`process_note` text,\n\t`contract_scan_id` text,\n\t`invoice_file_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `InvoiceRequest_contract_scan_id_unique` ON `InvoiceRequest` (`contract_scan_id`);--> statement-breakpoint\nCREATE UNIQUE INDEX `InvoiceRequest_invoice_file_id_unique` ON `InvoiceRequest` (`invoice_file_id`);--> statement-breakpoint\nCREATE INDEX `InvoiceRequest_matter_idx` ON `InvoiceRequest` (`matter_id`,`status`);--> statement-breakpoint\nCREATE INDEX `InvoiceRequest_status_idx` ON `InvoiceRequest` (`status`,`requested_at`);--> statement-breakpoint\nCREATE INDEX `InvoiceRequest_requester_idx` ON `InvoiceRequest` (`requested_by_id`);",
    "m0019": "CREATE TABLE `DocumentTemplate` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`category` text NOT NULL,\n\t`description` text,\n\t`applicable_categories_json` text DEFAULT '[]' NOT NULL,\n\t`docx_storage_key` text NOT NULL,\n\t`variables_json` text DEFAULT '[]' NOT NULL,\n\t`is_built_in` integer DEFAULT false NOT NULL,\n\t`enabled` integer DEFAULT true NOT NULL,\n\t`created_by_id` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `DocumentTemplate_category_idx` ON `DocumentTemplate` (`category`,`enabled`);--> statement-breakpoint\nALTER TABLE `Document` ADD `template_id` text;--> statement-breakpoint\nALTER TABLE `Document` ADD `template_context_json` text;",
    "m0020": "CREATE TABLE `MatterMember` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`matter_id` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`role` text DEFAULT 'ASSISTANT' NOT NULL,\n\t`joined_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `MatterMember_matter_user_uq` ON `MatterMember` (`matter_id`,`user_id`);--> statement-breakpoint\nCREATE INDEX `MatterMember_user_idx` ON `MatterMember` (`user_id`);",
    "m0021": "-- Custom SQL migration file, put your code below! --\n-- Backfill: mirror every existing matter's owner as its LEAD team member, so the\n-- roster invariant (owner is always present as LEAD) holds for matters created\n-- before the MatterMember table existed. Idempotent via NOT EXISTS; joined_at is\n-- the matter's own creation time (epoch seconds, matching the timestamp encoding).\nINSERT INTO `MatterMember` (`id`, `matter_id`, `user_id`, `role`, `joined_at`)\nSELECT lower(hex(randomblob(16))), m.`id`, m.`owner_id`, 'LEAD', m.`created_at`\nFROM `Matter` m\nWHERE NOT EXISTS (\n  SELECT 1 FROM `MatterMember` mm\n  WHERE mm.`matter_id` = m.`id` AND mm.`user_id` = m.`owner_id`\n);\n"
  }
} as const;
