/**
 * Embed the skills/ markdown into a TS module so the CLI can serve it from the
 * bundled binary (no filesystem lookup needed). Run by `build`/`prepare`; the
 * generated file is also committed so `tsx` dev works without a pre-step.
 * Re-run after editing any SKILL.md: `pnpm --filter @lawlink/cli gen:skills`.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const SKILLS_DIR = join("..", "..", "skills");

const field = (fm, key) => {
  const m = fm.match(new RegExp(`^\\s*${key}:\\s*"?(.+?)"?\\s*$`, "m"));
  return m ? m[1] : undefined;
};

const docs = [];
for (const domain of readdirSync(SKILLS_DIR, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort()) {
  const file = join(SKILLS_DIR, domain, "SKILL.md");
  if (!existsSync(file)) continue;
  const body = readFileSync(file, "utf8");
  const fm = (body.match(/^---\n([\s\S]*?)\n---/) ?? [, ""])[1];
  docs.push({
    domain,
    name: field(fm, "name"),
    version: field(fm, "version"),
    description: field(fm, "description"),
    cliHelp: field(fm, "cliHelp"),
    body,
  });
}

const readme = existsSync(join(SKILLS_DIR, "README.md")) ? readFileSync(join(SKILLS_DIR, "README.md"), "utf8") : "";

const out = `// AUTO-GENERATED by gen-skills.mjs from /skills — do not edit by hand.
export interface SkillDoc {
  domain: string;
  name?: string;
  version?: string;
  description?: string;
  cliHelp?: string;
  body: string;
}
export const SKILLS: SkillDoc[] = ${JSON.stringify(docs, null, 2)};
export const SKILLS_README: string = ${JSON.stringify(readme)};
`;

writeFileSync(join("src", "skills.generated.ts"), out);
console.log(`embedded ${docs.length} skills + router into src/skills.generated.ts`);
