/** Procedure vocabulary + the category→allowed-types mapping (DOMAIN-SPEC §4.2). */
import type { MatterCategory } from "../types.js";

export type ProcedureEngagement = "ENGAGED" | "INFORMATIONAL";
export type ProcedureStatus = "PENDING" | "IN_PROGRESS" | "CONCLUDED";

export type ProcedureType =
  | "FIRST_INSTANCE"
  | "SECOND_INSTANCE"
  | "RETRIAL_REVIEW"
  | "RETRIAL"
  | "REMAND_FIRST"
  | "REMAND_SECOND"
  | "PROSECUTORIAL_SUPERVISION"
  | "COMMERCIAL_ARBITRATION"
  | "LABOR_ARBITRATION"
  | "ARBITRATION_SET_ASIDE"
  | "ARBITRATION_ENFORCEMENT_REVIEW"
  | "ENFORCEMENT"
  | "ENFORCEMENT_OBJECTION"
  | "INVESTIGATION"
  | "PROSECUTION_REVIEW"
  | "DEATH_PENALTY_REVIEW"
  | "CRIMINAL_ENFORCEMENT"
  | "COMMUTATION_PAROLE_REVIEW"
  | "ADMIN_RECONSIDERATION"
  | "ADMIN_NON_LITIGATION_ENFORCEMENT"
  | "NON_LITIGATION_PHASE"
  | "CUSTOM";

/** Which procedure types each case category may use (DOMAIN-SPEC §4.2). */
export const PROCEDURES_BY_CATEGORY: Record<MatterCategory, ProcedureType[]> = {
  CIVIL_COMMERCIAL: [
    "FIRST_INSTANCE", "SECOND_INSTANCE", "RETRIAL_REVIEW", "RETRIAL",
    "REMAND_FIRST", "REMAND_SECOND", "COMMERCIAL_ARBITRATION", "LABOR_ARBITRATION",
    "ARBITRATION_SET_ASIDE", "ARBITRATION_ENFORCEMENT_REVIEW", "ENFORCEMENT",
    "ENFORCEMENT_OBJECTION", "PROSECUTORIAL_SUPERVISION", "CUSTOM",
  ],
  CRIMINAL: [
    "INVESTIGATION", "PROSECUTION_REVIEW", "FIRST_INSTANCE", "SECOND_INSTANCE",
    "DEATH_PENALTY_REVIEW", "RETRIAL_REVIEW", "RETRIAL", "CRIMINAL_ENFORCEMENT",
    "COMMUTATION_PAROLE_REVIEW", "PROSECUTORIAL_SUPERVISION", "CUSTOM",
  ],
  ADMINISTRATIVE: [
    "ADMIN_RECONSIDERATION", "FIRST_INSTANCE", "SECOND_INSTANCE", "RETRIAL_REVIEW",
    "RETRIAL", "ADMIN_NON_LITIGATION_ENFORCEMENT", "PROSECUTORIAL_SUPERVISION", "CUSTOM",
  ],
  NON_LITIGATION: ["NON_LITIGATION_PHASE", "CUSTOM"],
  LEGAL_COUNSEL: ["NON_LITIGATION_PHASE", "CUSTOM"],
  SPECIAL_PROJECT: ["NON_LITIGATION_PHASE", "CUSTOM"],
};

export function isProcedureAllowed(category: MatterCategory, type: ProcedureType): boolean {
  return PROCEDURES_BY_CATEGORY[category]?.includes(type) ?? false;
}
